---
title: "Gene_Name_Analysis"
output: html_document
date: "2023-02-28"
---

# Library
```{r}
library(readxl)
library(purrr)
library(vioplot)
library(stringr)
library(dplyr)
library(writexl)
library(plyr)
library(tidyverse)
```

# File path 
```{r}
data_dir <- file.path('.','Data_HSCF')
output_dir <- file.path('.', 'Output_HSCF')
```

# Read data
```{r}
# List all the excel files in the folder 
kid_excel_files <- list.files(file.path(data_dir),pattern = "*.xlsx")

# Read all the excel files listed above 
kids <- lapply(file.path(data_dir, kid_excel_files), read_excel)

# Check to see if we get all the 44 files 
num_kids <- length(kids) # output = 44

# Get the Gene_name column from each of these data frames 
kid_info <- lapply(kids, "[", ,"Gene_name") # Note - this contains only Gene_name column

# Unlist the list of lists into 1 big list 
gene_names_unlisted <- unlist(kid_info)

# Take out the Gene_name name from the list
gene_names_unnamed <- unname(gene_names_unlisted)

# Make the gene names a table and count
gene_count <- data.frame(table(gene_names_unnamed)) 

# Sort the gene counts
gene_count <- gene_count %>%arrange(desc(Freq))

# Change the name of the column 
colnames(gene_count) <- c("gene", "Freq")

# Result 
gene_count
```

# Matching Gene to Kid Name 

• Loop to check gene name for each kid
```{r}
# Extract kid names from the file names 
kid_names <- str_extract(kid_excel_files, "(?<=EC_).+(?=_variation.*)")

# Loop1: Run from here  to the end of this chunk
for (i in seq_along(kid_info)) {
  kid_info[[i]]$Kid_name <- kid_names[i]
}

# Create a vector of unique gene names from 'gene_names_unnamed'
all_gene_names <- unique(gene_names_unnamed)

# Loop over each gene and each kid, checking whether the current kid has the current gene
for( i in seq_along(kid_info)){
  kid_info[[i]]$Kid_Name <- kid_names[i]
}
all_gene_names <- unique(gene_names_unnamed)
for (gene in all_gene_names) {
  kids_with_gene <- ""
  kids_without_gene <- ""
  for (kid in kid_info) {
    if (any(kid$Gene_name == gene)) {
      if (kids_with_gene != "")
        kids_with_gene <- paste(kids_with_gene, kid$Kid_Name[1], sep=", ")
      else 
        kids_with_gene <- kid$Kid_Name[1]
    } else {
      if (kids_without_gene != "")
        kids_without_gene <- paste(kids_without_gene, ", ", kid$Kid_Name[1], sep="")
      else 
        kids_without_gene <- kid$Kid_Name[1]
    }
  }
  # Update `kid_names` and `kids_without` fields of `gene_count` data frame for the current gene
  gene_count$kid_with_gene[gene_count$gene == gene] <- kids_with_gene
  gene_count$kids_without[gene_count$gene == gene] <- kids_without_gene
}
```

• Loop to get Function that match Gene_name
```{r}
# Look at the result from the loop above 
view(gene_count)

# Subset dataframe to get function and Gene_name column
combined_df <- do.call(rbind, kids) # Enlist the kids dataframe 
function_df <- subset(combined_df, select = c("Gene_name", "Function"))

# Loop2: run from here to the end of this chunk
for (i in seq_len(nrow(gene_count))) {
  gene_name <- gene_count$gene[i]
  function_vale <- function_df$Function[function_df$Gene_name == gene_name]
  gene_count$Function[i] <- function_vale
}
```

• Export Data into Excel file 
```{r}
# Check the result 
view(gene_count)

# Export the data
write_xlsx(gene_count, file.path(output_dir, "SM_HSCF_gene_name_similarity.xlsx"))
```

# Looking into more detail for each kid 
```{r}
# Create a dataframe
genes_kids_dont_have <- data.frame("", "")
names(genes_kids_dont_have) <- c("Kid_name", "Genes_Without")

#Loop3:
for (kid in kid_info) {
  genes_without <- ""
  for (gene in all_gene_names) {
    if (!any(kid$Gene_name == gene)) {
      if (genes_without != "")
        genes_without <- paste(genes_without, ", ", gene, sep="")
      else 
        genes_without <- gene
    }
  }
  genes_kids_dont_have[nrow(genes_kids_dont_have) + 1,] = c(kid$Kid_Name[1], genes_without)
}

# Result
genes_kids_dont_have <- genes_kids_dont_have[-1,]
print(genes_kids_dont_have)
```

• Export Data
```{r}
write_xlsx(genes_kids_dont_have, file.path(output_dir, "AllGenesKidsDontHave.xlsx"))
```

# Look at the most populat gene for each kid 
```{r}
# Create a dataframe

genes_kids_dont_have <- data.frame("", "")
popular_genes <- gene_count$gene[gene_count$Freq > num_kids/2]
names(genes_kids_dont_have) <- c("Kid_name", "Genes_Without")

# Loop4:
for (kid in kid_info) {
  genes_without <- ""
  for (gene in popular_genes) {
    if (!any(kid$Gene_name == gene)) {
      if (genes_without != "")
        genes_without <- paste(genes_without, ", ", gene, sep="")
      else 
        genes_without <- gene
    }
  }
  genes_kids_dont_have[nrow(genes_kids_dont_have) + 1,] = c(kid$Kid_Name[1], genes_without)
}

#Result 
genes_kids_dont_have <- genes_kids_dont_have[-1,]
print(genes_kids_dont_have)
```

• Export Data
```{r}
write_xlsx(genes_kids_dont_have, file.path(output_dir, "GenesKidsDontHave.xlsx"))
```

